### PR TITLE
Update pkg_tar in the example to modern version.

### PR DESCRIPTION
**Pull request by jarondl**

### CODE REVIEW

**Comment by aiuto** [comment]
That looks reasonable, but it doesn't work. I don't have permissions to view your logs.

**Comment by aiuto** [comment]
From the logs:
```
Step #2: ERROR: /builder/home/.cache/bazel/_bazel_root/9577f47a4b74a1efac5f5b6bb332ae59/external/rules_pkg/pkg/private/pkg_files.bzl:407:12: name 'json' is not defined
Step #2: ERROR: Skipping '//:all': while parsing '//:all': error loading package '': in /builder/home/.cache/bazel/_bazel_root/9577f47a4b74a1efac5f5b6bb332ae59/external/rules_pkg/pkg/tar.bzl: in /builder/home/.cache/bazel/_bazel_root/9577f47a4b74a1efac5f5b6bb332ae59/external/rules_pkg/pkg/private/tar/tar.bzl: Extension 'pkg/private/pkg_files.bzl' has errors
Step #2: WARNING: Target pattern parsing failed.
```

The error about json would mean youi are using a bazel version before that module was available, so earlier than 4.0
https://blog.bazel.build/2021/01/19/bazel-4-0.html#starlark

You do need to update the bazel version. 4.0 is the minimal version we do long term support for.

**Comment by jarondl** [comment]
Thanks for that. This is built with cloudbuild, using gcr.io/cloud-marketplace-containers/google/bazel
I think I decided on this image from https://github.com/GoogleCloudPlatform/cloud-builders/blob/master/bazel/README.md 
But it seems to have been silently abandoned. I'll switch to the cloud-builders version.

**Comment by aiuto** [comment]
Now that the checks pass, someone with write access has to merge. I can't

**Comment by jarondl** [comment]
Merged, thanks for your help @aiuto

**Pull request merged**
