### PR TITLE
add: tags tagFileDevices - 1095

### PR DESCRIPTION
**Pull request by yakhatape**
Hi, the following PR is a proposal to add the flag number 1095 which is missing into the RPM Header Flags, which is a standard from the Linux foundation and from the native rpmbuild tools.

https://refspecs.linuxfoundation.org/LSB_3.0.0/LSB-Core-generic/LSB-Core-generic/swinstall.html
https://rpm-software-management.github.io/rpm/manual/tags.html

The impact of this missing Flag into the RPM Header is for some Redhat Satellite or Spacewalk/Katello repo manager etc.. which are checking the presence of this Flag cant import properly RPM Package build by rpmpack. Which provok an internal reposity inconsistance between of the public repository.

Exemple Elastic use the rpmpack since few month and our internal repository arent able to be updated with package built with rpmpack since their version >=v8.5.0 because the Flag 1095/FILEDEVICE it absent.
#https://github.com/elastic/apm-server/issues/11367

I'm staying at disposal if needed

### CODE REVIEW

**Comment by jarondl** [comment]
Very interesting. I guess we did not run into it, because our rpms install just fine.
Do you know if most rpms built with rpmbuild have this field? And is the value reliably `1`? I don't want to break other users.
Is there any way to add a test case?

/gcbrun

**Comment by jarondl** [comment]
Ping @yakhatape 
It's ok if you don't have answers for my questions, just let me know :)

**Comment by caarlos0** [comment]
judging by rpm's src, seems like it's always 1 indeed: https://github.com/rpm-software-management/rpm/blob/c167ef8bdaecdd2e306ec896c919607ba9cceb6f/build/files.c#L1226

**Comment by jarondl** [comment]
Thanks for checking @caarlos0 ! What do you say, should we merge this?

@yakhatape are you there? Can you sync the tags.go file please?

**Comment by caarlos0** [comment]
I think so

FWIW, I ran nfpm's RPM test suite against this as well, and everything seems ok
CleanShot 2024-02-15 at 16 20 55@2x

**Comment by yakhatape** [comment]
@jarondl sorry for the delay I got some personnal issue to follow the subject.

I've fixe the conflict from master into the branch, can you do the gcbrun ?

thanks for all your help ;)

**Comment by jarondl** [comment]
Hi @yakhatape , no problem about delays, I often have them too. Have you seen my comment in line 464 of rpm.go? Please add a comment explaining what 1 is. (Or what we think it is).

**Comment by yakhatape** [comment]
@jarondl all done

**Comment by jarondl** [comment]
Thank you very much @yakhatape for your contribution!

**Pull request merged**
