### PR TITLE
fix sense bitmask

### PR DESCRIPTION
**Pull request by rbtr**
closes https://github.com/google/rpmpack/issues/31

### CODE REVIEW

**Comment by rbtr** [comment]
nudge @jarondl @djgilcrease

**Comment by rbtr** [comment]
fwiw the CLI is signed and has been reporting OK until the latest push :thinking:

**Comment by jarondl** [comment]
Thank you very much for your contribution!

**Comment by rbtr** [comment]
@jarondl if this is good can we get a merge/tag so that [nfpm/goreleaser](https://github.com/goreleaser/nfpm/issues/94) can update their usages? thanks!

**Comment by jarondl** [comment]
\

> fwiw the CLI is signed and has been reporting OK until the latest push thinking

I don't know what's up with the CLA assistant, or how to force it to check the status again.. I cannot merge without it. I'll check tomorrow.

**Comment by rbtr** [comment]
@jarondl force-pushed to trigger the webhooks and CLA caught on :)

**Comment by jarondl** [comment]
> @jarondl if this is good to go can we get a merge/tag so that [nfpm and goreleaser](https://github.com/goreleaser/nfpm/issues/94) can update their usages? thanks!

done v0.3

**Comment by rbtr** [comment]
thanks!

**Pull request merged**
