### PR TITLE
fix: handle packager, vendor and others

### PR DESCRIPTION
**Pull request by caarlos0**
Packager, vendor, URL, and Epoch are being added to the headers even if they have no value and are not required.

This PR moves them to pointers, and add them if they are non-null values.

Could also not add them if they have their default value, which would not break anyone using the lib, but might be less clear, especially if someone wants to set epoch to 0, for example...

refs https://github.com/goreleaser/nfpm/issues/619

### CODE REVIEW

**Comment by jarondl** [comment]
Thank you!
So this is a breaking API change, right? I don't think we can simply push such a change without breaking anybody.
OTOH, using default values seems ok for strings, but I explicitly use `epoch=0` in some of my code, to match other "repeatable builds" tooling.

Quite a conundrum.

**Comment by caarlos0** [comment]
Yes, this will unfortunately be a breaking change... 
I do think this is a change that should be made, though, even though the resulting rpm isn't  exactly invalid, it is forbidden by rpmbuild, so probably there's a reason for that 🤔

**Comment by caarlos0** [comment]
another idea would be to reserve values and use them instead e.g.

```go
const NO_EPOCH = ^uint32(0)

if epoch != NO_EPOCH {
 // add field
}
```

wdyt?

**Comment by jarondl** [comment]
Ohhhh using 4294967295 .. That's gross; I like it. OK I don't like it, but better it's than the alternative. Can you make the change? Be sure to include the literal 4294967295 in the code comment, and say why we went that route.

**Comment by caarlos0** [comment]
pushed, let me know what you think!

**Pull request merged**
